# Alexa Prompts Language Constants

SKILL_NAME = "SKILL_NAME"
GET_CRITICAL_MESSAGE = "GET_CRITICAL_MESSAGE"
HELP_MESSAGE = "HELP_MESSAGE"
HELP_REPROMPT = "HELP_REPROMPT"
FALLBACK_MESSAGE = "FALLBACK_MESSAGE"
FALLBACK_REPROMPT = "FALLBACK_REPROMPT"
ERROR_MESSAGE = "ERROR_MESSAGE"
STOP_MESSAGE = "STOP_MESSAGE"
CRITICALS = "CRITICALS"
ROLL_MESSAGE = "ROLL_MESSAGE"